### ISSUE TITLE
ClassCastException in StringLiteralExpr.java:26

### ISSUE THREAD

**Issue by oalekseev** [cwong15/freemarker-introspection#2]
for templates like this "'some text ${foo1} some text ${foo2} some text'"

java.lang.ClassCastException: java.lang.String cannot be cast to freemarker.core.TemplateElement

	at freemarker.introspection.StringLiteralExpr.getDynamicValue(StringLiteralExpr.java:26)
	at freemarker.introspection.variables.VariableFinder.visit(VariableFinder.java:239)
	at freemarker.introspection.BaseExpr.accept(BaseExpr.java:62)
	at freemarker.introspection.variables.VariableFinder.scanParams(VariableFinder.java:195)
	at freemarker.introspection.variables.VariableFinder.visit(VariableFinder.java:117)
	at freemarker.introspection.BaseElement.accept(BaseElement.java:83)
	at freemarker.introspection.variables.VariableFinder.seek(VariableFinder.java:62)

**Comment by oalekseev** [comment]
this is a fix changes

freemarker.introspection.StringExpr
![StringExpr](https://user-images.githubusercontent.com/5575088/94842929-a2b47000-0424-11eb-843f-c41f4ca629fd.png)

freemarker.introspection.StringLiteralExpr
![StringLiteralExpr](https://user-images.githubusercontent.com/5575088/94842933-a34d0680-0424-11eb-9649-df6b3ae0c1bb.png)

freemarker.introspection.variables.VariableFinder (method void visit(Expr expr))
![VariableFinder](https://user-images.githubusercontent.com/5575088/94842934-a3e59d00-0424-11eb-97e4-44dcc45fc8aa.png)

And test for template "'some text ${foo1} some text ${foo2} some text'"
freemarker.introspection.ExprParamsTests
![ExprParamsTests](https://user-images.githubusercontent.com/5575088/94842935-a3e59d00-0424-11eb-94dc-f5d954835d19.png)
And add import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertTrue;
