### ISSUE TITLE
IndexOutOfBoundsException in VariableFinder.java:290

### ISSUE THREAD

**Issue by oalekseev** [cwong15/freemarker-introspection#3]
for thise temlates
<#macro m><#local x></#local>[${x}]</#macro><@m/>${x!}
or
<#setting locale = 'de_DE'><#import 'lib.ftl' as lib>[${history!}] <#setting locale = 'en'><@lib.m/> ${lib.initLocale} [${history}]

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at freemarker.introspection.variables.VariableFinder.processDefaults(VariableFinder.java:290)
	at freemarker.introspection.variables.VariableFinder.visit(VariableFinder.java:227)
	at freemarker.introspection.BaseExpr.accept(BaseExpr.java:62)
	at freemarker.introspection.variables.VariableFinder.scanParams(VariableFinder.java:195)
	at freemarker.introspection.variables.VariableFinder.visit(VariableFinder.java:117)
	at freemarker.introspection.BaseElement.accept(BaseElement.java:83)
	at freemarker.introspection.BaseElement.accept(BaseElement.java:86)
	at freemarker.introspection.variables.VariableFinder.seek(VariableFinder.java:62)

**Comment by oalekseev** [comment]
This is a fix
![VariableFinder 3](https://user-images.githubusercontent.com/5575088/95009319-dc09fd00-0629-11eb-942a-fb94cf8b7c97.png)
