### ISSUE TITLE
lang.IndexOutOfBoundsException in VariableFinder.java:101

### ISSUE THREAD

**Issue by oalekseev** [cwong15/freemarker-introspection#4]
For thise templates 
<#list list><#items as it>${it!'null'}<#sep>, </#items></#list>
<#list 1..2 as x><#list 3..4>${x}:<#items as x>${x}</#items></#list>;</#list>
<#list 1..1><#items as x></#items><#items as x></#items></#list>
<#list (1..3)?map(p -> p * 10 + it!'-')><#items as it>${it}<#sep>, </#items></#list>

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at freemarker.introspection.variables.VariableFinder.visit(VariableFinder.java:101)
	at freemarker.introspection.BaseElement.accept(BaseElement.java:83)
	at freemarker.introspection.variables.VariableFinder.seek(VariableFinder.java:62)
	at Test.main(Test.java:62)

**Comment by oalekseev** [comment]
this is a fix
![VariableFinder 2](https://user-images.githubusercontent.com/5575088/95008970-e24aaa00-0626-11eb-9d74-ef6355c6b5d1.png)
